### ISSUE TITLE
Attempting to use a wave spawner in Peaceful mode breaks the spawner permanently

### ISSUE THREAD

**Issue by UnLuCkYcHaRrnS** [Geek202/FallFest2020#5]
I accidentally forgot to change the difficulty from peaceful after fortifying and customizing a dungeon house, and now it is all for nothing because I can't get the spawner to work again

**Comment by Tom-The-Geek** [comment]
I have known about this problem for a while, but haven't gotten round to fixing it yet.

Here's a temporary fix:
If you use Open To LAN to enable cheats, you should be able to use `/setblock <spawner x> <spawner y> <spawner z> air` and then `/setblock <spawner x> <spawner y> <spawner z> ttg_fallfest:cursed_spawner` to restore the state

**Comment by UnLuCkYcHaRrnS** [comment]
Placing the block as such works, but the game crashes when I try to activate it now, here is the crash report:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 10/27/20 8:41 PM
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: 0
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:60)
	at me.geek.tom.fallfest.block.spawner.CursedSpawnerController.beginSpawning(CursedSpawnerController.java:214)
	at me.geek.tom.fallfest.block.spawner.CursedSpawnerController.updateState(CursedSpawnerController.java:135)
	at me.geek.tom.fallfest.block.spawner.CursedSpawnerController.tickCharging(CursedSpawnerController.java:122)
	at me.geek.tom.fallfest.block.spawner.CursedSpawnerController.tick(CursedSpawnerController.java:100)
	at me.geek.tom.fallfest.block.spawner.CursedSpawnerBlockEntity.method_16896(CursedSpawnerBlockEntity.java:113)
	at net.minecraft.class_1937.method_18471(class_1937.java:510)
	at net.minecraft.class_3218.method_18765(class_3218.java:424)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:868)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:808)
	at net.minecraft.class_1132.method_3748(class_1132.java:92)
	at net.minecraft.server.MinecraftServer.handler$cic000$modifiedRunLoop(MinecraftServer.java:7297)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:648)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:60)
	at me.geek.tom.fallfest.block.spawner.CursedSpawnerController.beginSpawning(CursedSpawnerController.java:214)
	at me.geek.tom.fallfest.block.spawner.CursedSpawnerController.updateState(CursedSpawnerController.java:135)
	at me.geek.tom.fallfest.block.spawner.CursedSpawnerController.tickCharging(CursedSpawnerController.java:122)
	at me.geek.tom.fallfest.block.spawner.CursedSpawnerController.tick(CursedSpawnerController.java:100)
	at me.geek.tom.fallfest.block.spawner.CursedSpawnerBlockEntity.method_16896(CursedSpawnerBlockEntity.java:113)

-- Block entity being ticked --
Details:
	Name: ttg_fallfest:cursed_spawner // me.geek.tom.fallfest.block.spawner.CursedSpawnerBlockEntity
	Block: Block{ttg_fallfest:cursed_spawner}[active=true]
	Block location: World: (-132,51,-22), Chunk: (at 12,3,10 in -9,-2; contains blocks -144,0,-32 to -129,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Block: Block{ttg_fallfest:cursed_spawner}[active=true]
	Block location: World: (-132,51,-22), Chunk: (at 12,3,10 in -9,-2; contains blocks -144,0,-32 to -129,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at net.minecraft.class_1937.method_18471(class_1937.java:510)
	at net.minecraft.class_3218.method_18765(class_3218.java:424)

-- Affected level --
Details:
	All players: 1 total; [class_3222['UnLuCkYcHaRrnS'/278, l='ServerWorld minecraft:overworld Eldritch Survival', x=-127.48, y=50.00, z=-28.90]]
	Chunk stats: ServerChunkCache: 2275
	Level dimension: minecraft:overworld
	Level spawn location: World: (-80,64,-112), Chunk: (at 0,4,0 in -5,-7; contains blocks -80,0,-112 to -65,255,-97), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1366115 game time, 70392 day time
	Level name: Eldritch Survival
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 134781 (now: false), thunder time: 5693 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:868)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:808)
	at net.minecraft.class_1132.method_3748(class_1132.java:92)
	at net.minecraft.server.MinecraftServer.handler$cic000$modifiedRunLoop(MinecraftServer.java:7297)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:648)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6518430040 bytes (6216 MB) / 8423211008 bytes (8033 MB) up to 8423211008 bytes (8033 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx8192m
	Fabric Mods: 
		adventurez: AdventureZ 1.1.3
		amecsapi: Amecs API 1.1.1+mc1.16-rc1
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		appleskin: AppleSkin 1.0.11
		artifice: Artifice 0.13.2+1.16.3
		autoconfig1u: Auto Config v1 Updated 3.2.2
		autofish: Autofish 0.9.0
		automated_crafting: Automated Crafting 1.3.11-beta.1+MC1.16.2-1.16.3
		backpackmod: Backpack Mod 1.16.3-1.2.2
		backslot: BackSlot 1.1.6
		backslotaddon: BackSlot Addon 1.0.2
		beachslimes: Beach Slimes 2.1.0+mc1.16.1
		beaconsforall: Beacons For All 1.3.0-1.16.3
		bedspreads: Bedspreads 1.2.0-1.16.3
		better_mod_button: Better Mod Button 1.1.4
		betterf3: BetterF3 1.1.1
		betterstones: Better Stones 0.0.4
		betterthanmending: BetterThanMending 1.2.0
		bigbuckets: Big Buckets 2.0.0
		blockshifter: Blockshifter 1.3.1+fabric-1.16.2
		blue_endless_jankson: jankson 1.2.0
		bno: Basic Nether Ores 1.16.3-5.3.0-Fabric
		bruteimitation: Brute Imitation 1.0.0
		caelus: Caelus API 0.0.9-1.16.3
		cardinal-components-base: Cardinal Components API (base) 2.6.0
		cardinal-components-entity: Cardinal Components API (entities) 2.6.0
		cardinal-components-util: Cardinal Components API (utilities) 2.6.0
		carpet: Carpet Mod in Fabric 1.4.12
		cavebiomes: Cave Biomes 0.5.1
		chainmail: Chainmail 0.5.0
		clear-skies: Clear Skies 1.5.48
		cloth-api: Cloth API 1.4.8
		cloth-armor-api-v1: Cloth Armor API v1 1.4.8
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.8
		cloth-common-events-v1: Cloth Common Events v1 1.4.8
		cloth-config2: Cloth Config v4 4.8.2
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.8
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.8
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.8
		cloth-scissors-api-v1: Cloth Scissors API v1 1.4.8
		cloth-utils-v1: Cloth Utils v1 1.4.8
		colormatic: Colormatic 2.2.7+mc.1.16.3
		colytra: Colytra 1.2.0-1.16.3
		convenient-mobgriefing: Convenient mobGriefing 1.1.3
		craftablehorsearmour: Craftable Horse Armour & Saddle 1.16-1.3-Fabric
		crawl: Crawl 0.7.5
		crookedcrooks: Crooked Crooks 1.3.1+1.16.3
		crowmap: Crowmap 1.0.1
		cursedearth: Cursed Earth 2.0
		custom-crosshair-mod: Custom Crosshair Mod 1.0.3-fabric
		danceofgrowth: Dance Of Growth 1.0.0-1.16.2
		disablecustomworldsadvice: Disable Custom Worlds Advice 1.1
		doublejump: Double Jump Mod 1.16.1-1.0.0
		duplegg: DuplicatEgg 1.0.1
		dynamicsoundfilters: Dynamic Sound Filters 1.1.3+1.16.2
		eldritch_mobs: Eldritch Mobs 1.5.1
		elytra-recipe: Elytra Recipe 1.0.1
		elytra_bounce: Elytra Hopping 0.1.0+1.16.1
		elytraautoflight: Elytra Auto Flight 1.0.0
		enchantablehorsearmor: Enchantable Horse Armor 1.0a
		enchantedtooltips: Enchanted ToolTips 1.3.4-1.16
		enderitemod: Enderite Mod 1.2.2
		enderlift: Enderlift 1.0.5
		environmentz: EnvironmentZ 1.0.3
		expandedstorage: ExpandedStorage 5.6.30
		fabric: Fabric API 0.24.1+build.412-1.16
		fabric-api-base: Fabric API Base 0.2.0+9f0fb4b895
		fabric-biome-api-v1: Fabric Biome API (v1) 2.0.0+c29459ab95
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339895
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.2+f8ac1db295
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963695
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
		fabric-language-scala: Fabric Language Scala 0.3.2.12
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.0+c270b09895
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea18895
		fabric-ofcapes: Fabric OF Capes 1.2.0
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.0+9f0fb4b895
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.2+2b46237995
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.2+2b46237995
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb895
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+2b46237995
		fabricloader: Fabric Loader 0.10.3+build.211
		fairenchanting: FairEnchanting 1.2.0
		flight_display: Critical Flight Display 1.1.2
		flora-doubling: Flora Doubling 1.2.0
		fst: Fire's Survival Tweaks 2.0.0
		gravel-ores: Gravel Ores 1.2.0+1.16.2
		greater_eye: Greater Eye of Ender 1.1.1
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		harmfulstonecutters: Harmful Stonecutters 1.0.1
		harvest_scythes: Harvest Scythes 1.0.3
		horsestatsvanilla: Horse Stats Vanilla 4.1.4
		houraielixir: Hourai Elixir 1.16.3-1
		imm_ptl_core: Immersive Portals Core 0.39
		immersive_portals: Immersive Portals 0.39
		instantlava: InstantLava 1.2.1
		ironchest: Iron Chests 1.1.2
		jankson: Jankson 3.0.1+j1.2.0
		kyrptconfig: Kytpt Config 1.1.4-1.16
		libblockattributes: LibBlockAttributes 0.8.1
		libblockattributes_core: LibBlockAttributes (Core) 0.8.1
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.1
		libblockattributes_items: LibBlockAttributes (Items) 0.8.1
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.0.0+1.16.3
		libstructure: Libstructure 1.3
		lightlevel: Light Level 2.0.0
		linkart: Linkart unspecified
		linkedstorage: Linked Storage 1.3.11-1.16
		lithium: Lithium 0.5.6
		logical_zoom: Logical Zoom 0.0.5
		manhunt: Manhunt Fabric 0.4.0
		mcdict: MCDict 1.0.0+1.16.2
		minecraft: Minecraft 1.16.3
		mjmod: Daggers 1.0.0
		mm: Manningham Mills 2.1
		mobrebirth: Mob Rebirth 9.0.1
		modid: Damage Tilt 1.16-fabric-0.1.0
		modmenu: Mod Menu 1.14.6+build.31
		mooblooms: Mooblooms 1.3.2
		mutuality: Mutuality 1.0.0
		netheritehorsearmor: Netherite Horse Armor 0.4.3-1.16.3
		notchify: Notchify 0.2.3
		olifantenpad: Olifantenpad 1.0.0
		overpowered_mending: Overpowered Mending 2.2.2
		peepingcreepers: Peeping Creepers 1.1
		pehkui: Pehkui 1.6.2+1.16.3
		phosphor: Phosphor 0.6.0+build.7
		portalcrafter: Portal Crafter 1.0.0
		potiontipped: Potion Tipped 1.0.0
		pumice: Pumice 0.0.2
		quickshulker: Quick Shulker 1.1.10-1.16
		recently_used: Recently Used 0.2.2+1.16.1
		repairableanvils: Repairable Anvils 0.0.2
		resourceloader: Fabric Resource Loader 1.1.1
		rottenflesh2leather: Rotten Flesh To Leather [FABRIC] 1.0.0
		seasons: Fabric Seasons 0.3-BETA
		shulkerboxtooltip: Shulker Box Tooltip 2.3.1+1.16.3
		snowy_leaves: Snowy Leaves 1.16.1-1.3.1
		sodium: Sodium 0.1.0-SNAPSHOT
		stackablepotions: Stackable Potions 1.0.0
		staffofbuilding: Staff of Building 1.2.3-1.16.2
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		suitablystackablestew: Suitably Stackable Stew 1.1.1
		telepistons: Telepistons 1.0.1
		torohealth: ToroHealth Damage Indicators 1.16.3-fabric-1
		totemmod: Wither Totems Mod 0.3.1
		tridentfixer: Repairable Tridents 1.0.0
		trinket-heart-canisters: Trinket Heart Canisters 1.0.0
		trinkets: Trinkets 2.6.5
		ttg_fallfest: FallFest 2020 0.1.1
		unforgivingvoid: Unforgiving Void 2.0.0
		unlimiter: Unlimiter 1.3.0
		unsuspicious-stew: Unsuspicious Stew 0.1
		voyager: Voyager 1.0.0
		waystones: Waystones 1.0.8
		whiplash: Whiplash: Magic Dungeons 1.0.0
		wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
		world_blender: World Blender 1.16.3-1.0.5
		xaerominimap: Xaero's Minimap 20.26.0
		xpbeacon: Experience Beacons 2.0
		xpstorage: XP Storage 1.1.1+1.16.3
		zoob: Monster Of The Ocean Depths 1.0.0
	Player Count: 1 / 8; [class_3222['UnLuCkYcHaRrnS'/278, l='ServerWorld minecraft:overworld Eldritch Survival', x=-127.48, y=50.00, z=-28.90]]
	Data Packs: vanilla, fabric/trinkets, fabric/adventurez, fabric/staffofbuilding, fabric/eldritch_mobs, fabric/trinket-heart-canisters, fabric/betterstones, fabric/world_blender, fabric/totemmod, fabric/pumice, fabric/greater_eye, fabric/flora-doubling, fabric/fst, fabric/blockshifter, fabric/fabric-tool-attribute-api-v1, fabric/enderitemod (incompatible), fabric/enderlift, fabric/backpackmod, fabric/potiontipped, fabric/expandedstorage, fabric/mjmod, fabric/environmentz, fabric/linkedstorage, fabric/libcd, fabric/cavebiomes, fabric/automated_crafting, fabric/colytra, fabric/gravel-ores, fabric/waystones, fabric/portalcrafter, fabric/cursedearth, fabric/netheritehorsearmor, fabric/bno, fabric/seasons, fabric/wolveswitharmor, fabric/elytra-recipe, fabric/linkart, fabric/bedspreads, fabric/ironchest, fabric/ttg_fallfest, fabric/crookedcrooks, fabric/xpstorage, fabric/mooblooms, fabric/zoob, fabric/craftablehorsearmour, fabric/bigbuckets (incompatible), fabric/whiplash, Resource Loader pack, fabric/beachslimes, fabric/rottenflesh2leather
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by Tom-The-Geek** [comment]
Hmm. Try `/setblock <spawner x> <spawner y> <spawner z> ttg_fallfest:cursed_spawner{"Profile":"ttg_fallfest:spawner_room"}`. The crash is not correct, as it should simply warn if it is using the default empty profile.
